{"name": "Создание уникального пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n +  where 403 = <Response [403]>.status_code", "trace": "self = <test_01_create_user.TestCreateUser object at 0x10225e960>\ncreate_user_data = {'token': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmZiNGZhOWVkMjgwMDAxYjUwZDE0ZSIsImlhdCI6MTczMTE3OTc...: {'email': '9021817c-ba58-4b7a-86b2-f1b07dd35cf6@example.com', 'name': 'UniqueUser', 'password': 'securePassword123'}}\n\n    @allure.title(\"Создание уникального пользователя\")\n    def test_create_unique_user(self, create_user_data):\n        response = requests.post(DataUrl.BASE_URL + self.endpoint, json=create_user_data)\n    \n>       assert response.status_code == 200\nE       assert 403 == 200\nE        +  where 403 = <Response [403]>.status_code\n\ntests/test_01_create_user.py:14: AssertionError"}, "start": 1731179770342, "stop": 1731179771033, "uuid": "4eb7f155-a503-48be-8431-9b71299ecbc6", "historyId": "f9380b14c65797208cbb7f2dcbf7aaf2", "testCaseId": "f9380b14c65797208cbb7f2dcbf7aaf2", "fullName": "tests.test_01_create_user.TestCreateUser#test_create_unique_user", "labels": [{"name": "story", "value": "1. Создание пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_01_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "MBP-Vlad"}, {"name": "thread", "value": "8112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_01_create_user"}]}